accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
   
    path('collab/', views.collab_form , name ="collaborate_form"),
    path('signin/', views.signin, name="signin"),  
    path('signout/', views.signout, name='signout'),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.user_profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    
]

blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'
urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('add/', views.add_recipe, name='add_recipe'),
    path('category/<int:category_id>/', views.category_recipes, name='category_recipes'), 
    path('recipe/edit/<slug:slug>/', views.edit_recipe, name='edit_recipe'),
    path('recipe/delete/<slug:slug>/', views.delete_recipe, name='delete_recipe'),
    path('recipes/', views.recipe_list, name='recipe_list'),
    path('<slug:slug>/', views.recipe_detail, name='recipe_detail'),
    
]

codestar/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("allauth.urls")),
    path('pages/', include('pages.urls')),
    path('summernote/', include('django_summernote.urls')),
    path("", include("blog.urls"), name='blog-urls'),
]

pages/urls.py
from . import views
from django.urls import path

app_name = 'pages'  # Updated the app_name

urlpatterns = [
    path('', views.page_diet, name='page_diet'),  
]

templates/base.html
{% load static %}
{% url 'home' as home_url %}
<!-- {% url 'logout' as logout_url %}
{% url 'signin' as signin_url %}
{% url 'signup' as signup_url %} -->


<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title class="title">  Flavour Nest | Mediterranean Diet Recipe Collection</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/NestLogo.jpg' %}" type="image">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mea+Culpa&display=swap" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light sticky-top">
        <div class="container-fluid">
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse show" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url 'blog:recipe_list' %}">Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'pages:page_diet' %}">The Mediterranean Diet ? </a>
                    </li>
                </ul>

                <!-- User Authentication Links or Profile -->
                <ul class="navbar-nav mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <!-- Profile Picture with Dropdown Menu -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {% if "placeholder" in user.profile.profile_image.url %}
                            <img class="profile-pic" src="{% static 'images/nobody.jpg' %}"
                              alt="placeholder image">
                            {% else %}
                            <img src="{{user.profile.profile_image.url }}" alt="Profile Picture" class="profile-pic">
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
                            <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">My Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Settings</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'accounts:signout' %}">Log Out</a></li>
                        </ul>
                    </li>
                    {% else %}
                    
                    <!-- Login and Register Links for Unauthenticated Users -->
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                            href="{% url 'accounts:signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == signin_url %}active{% endif %}" aria-current="page"
                            href="{% url 'accounts:signin' %}">Login</a>
                    </li>
                    

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- displaying Django messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible
          fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <main class="flex-shrink-0 main-bg">
        <a class="navbar-brand d-flex flex-column" href="/" aria-label="Click flavour nest logo to go to home page">
            <span class="brand">Flavour<span class="thin-coral">Nest</span></span>
            <span class="navbar-subtitle">A Mediterranean Diet Recipe Collection</span>
        </a>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer>
        <div class="container px-4">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://facebook.com" target="_blank"
                                aria-label="Visit our Facebook page (opens in a new tab)">
                                <span class="fa-stack fa-lg">
                                    <i class="fa-brands fa-facebook fa-stack-1x social-icon" aria-hidden="true"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://instagram.com" target="_blank"
                                aria-label="Visit our Instagram page (opens in a new tab)">
                                <span class="fa-stack fa-lg">
                                    <i class="fa-brands fa-instagram fa-stack-1x social-icon" aria-hidden="true"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://youtube.com" target="_blank"
                                aria-label="Visit our YouTube page (opens in a new tab)">
                                <span class="fa-stack fa-lg">
                                    <i class="fa-brands fa-youtube fa-stack-1x social-icon" aria-hidden="true"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="m-0 text-center contact-text-email">
                        <i class="fa-solid fa-envelope social-icon" aria-hidden="true"></i>
                        <a href="mailto:info@statementbeauty.com">info@flavournest.com</a>
                    </p>
                    <p class="m-0 text-center footer-text">
                        Whisked Up By © Meryem Essalhi 2025
                        <a href="https://github.com/Mery369" target="_blank"
                            aria-label="Visit our GitHub page (opens in a new tab)">
                            <span class="fa-stack fa-lg">
                                <i class="fa-brands fa-github fa-stack-1x social-icon" aria-hidden="true"></i>
                            </span>
                        </a>
                    </p>
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
            </script>
        <script src="https://kit.fontawesome.com/b205b6285d.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </footer>
</body>

</html>